services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    ports:
      - "8180:8080"
    environment:
      TZ: Asia/Tokyo
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: dev-file
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm.json
      - keycloak-data:/opt/keycloak/data
    command: start-dev --import-realm

  spa-gateway:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/workspace
      - gradle-cache:/home/vscode/.gradle
    command: sleep infinity
    depends_on:
      - keycloak

volumes:
  keycloak-data:
  gradle-cache:
